#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="$( cd ${MY_DIR}/../../.. && pwd )"
SCRIPTS_DIR="$( cd "${MY_DIR}/../" && pwd )"
DEPLOYMENTS_DIR="${WORKSPACE_DIR}/${DEPLOYMENTS_RELATIVE_DIR:?}"
RELEASE_DIR="${WORKSPACE_DIR}/${RELEASE_RELATIVE_DIR:?}"
OUTPUT_FILE_LOCATION="${WORKSPACE_DIR}/${OUTPUT_FILE_RELATIVE_LOCATION:?}"
stub_location=/tmp/cf-mysql-acceptance-tests-stub.yml


echo "ENV: ${ENV:?}"

source ${SCRIPTS_DIR}/scripts/utils.sh

echo "args: $*"

cat > ${stub_location} <<EOF
---
jobs:
- name: acceptance-tests
  properties:
    smoke_tests_only: false
EOF

pushd ${RELEASE_DIR}
  ./generate_deployment_manifest \
    aws \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-aws-stub.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-networks-stub.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-shared-secrets.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-mysql-plans-stub.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-properties.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-mysql-secrets.yml \
    ${stub_location} \
     > ${OUTPUT_FILE_LOCATION}

popd
