---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: bosh-lite-info

run:
  path: cf-mysql-ci/scripts/bosh-lite-orange/bosh-lite-env

params:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_CA_CERT_PATH:
  ENV_TARGET_FILE:        
