#!/bin/bash
set -eux

BBL_GIT_TAG=`cat bbl-github-release/tag`
BOSH_CLI_VERSION=`cat bosh-cli-github-release/version`

cat << EOF > docker-build-args/docker-build-args.json
{
  "BBL_GIT_TAG": "${BBL_GIT_TAG}",
  "BOSH_CLI_VERSION": "${BOSH_CLI_VERSION}"
}
EOF
