#!/usr/bin/env bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="${MY_DIR}/../../../"
RELEASE_DIR="${WORKSPACE_DIR}/pxc-release"

export BOSH_ENVIRONMENT=$(cat bosh-lite-info/external-ip)
export BOSH_CA_CERT_PATH="${WORKSPACE_DIR}/bosh-lite-info/ca-cert"
export MYSQL_USERNAME=root
export MYSQL_PASSWORD=$(bosh int varstore/deployment-vars.yml --path /cf_mysql_mysql_admin_password)

source ${RELEASE_DIR}/.envrc # To set GOPATH to release dir
go install -v github.com/onsi/ginkgo/ginkgo
pushd ${RELEASE_DIR}/src/specs/integration
  echo "Running tests ..."
  ginkgo scaling
popd
