#!/bin/bash

set -eux

tmpdir=$(mktemp -d /tmp/mysql_scaling.XXXXX)
trap '{ rm -rf ${tmpdir}; }' EXIT

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd "${MY_DIR}/../../" && pwd )"
WORKSPACE_DIR="$( cd "${MY_DIR}/../../../" && pwd )"

source "${MY_DIR}/scaling-helpers"

setup_infrastructure_variables 10.244.7.2 10.244.8.2 10.244.9.2

pushd "${MY_DIR}"
  bundle install
popd

bosh -n target "${DIRECTOR_IP}"
bosh -n login "${BOSH_USER}" "${BOSH_PASSWORD}"

clear_data
write_some_data 1000

deploy_full_cluster #this step removes the arbitrator
verify_replicated_row_count_is 1000

scale_down_to_minimal
write_some_data 1000
verify_first_node_row_count_is 2000

echo "Success!"
