#!/bin/bash

set -eux

tmpdir=$(mktemp -d /tmp/mysql_scaling.XXXXX)
trap '{ rm -rf ${tmpdir}; }' EXIT

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd "${MY_DIR}/../../" && pwd )"
WORKSPACE_DIR="$( cd "${MY_DIR}/../../../" && pwd )"

source "${MY_DIR}/scaling-helpers"

setup_infrastructure_variables

pushd "${MY_DIR}"
  bundle install
popd

bosh -n target "${DIRECTOR_IP}"
bosh -n login "${BOSH_USER}" "${BOSH_PASSWORD}"

scale_down
clear_data
write_some_data 1000

scale_up
verify_replicated_row_count_is 1000

scale_down
write_some_data 1000
verify_first_node_row_count_is 2000

echo "Success!"
