#!/bin/bash

set -e -x

GIT_PRIVATE_KEY=${GIT_PRIVATE_KEY:?}
echo "$GIT_PRIVATE_KEY" > git-private-key-file
chmod 0600 git-private-key-file

eval $(ssh-agent)
ssh-add git-private-key-file

cd cf-mysql-release

CURRENT_TESTED_COMMIT=$(git rev-parse HEAD)

git checkout release-candidate

git merge ${CURRENT_TESTED_COMMIT}

git push origin release-candidate
