#!/bin/bash

set -e -x

GIT_PRIVATE_KEY=${GIT_PRIVATE_KEY:?}
echo $GIT_PRIVATE_KEY > git-private-key-file
chmod 0600 git-private-key-file

eval $(ssh-agent)
ssh-add git-private-key-file

cd cf-mysql-release

git checkout release-candidate

git rebase develop

#git push origin release-candidate
