#!/bin/bash -exu

ROOT_DIR=$PWD

cp ${ROOT_DIR}/release-notes/RELEASE_NOTES_v* "${ROOT_DIR}/output-release-dir/generated-release-notes"
echo "v$(cat ${ROOT_DIR}/version/version)" > "${ROOT_DIR}/output-release-dir/cf-mysql-tag"

pushd "${ROOT_DIR}/cf-mysql-committed/cf-mysql-release-final"
  git rev-parse HEAD > "${ROOT_DIR}/output-release-dir/git-commit"
popd
