#!/usr/bin/env bash

bosh_release_version="$(cat last-pxc-release-bosh-release/version)"
github_release_version="$(cat last-pxc-release-source/version)"

if [ "$bosh_release_version" != "$github_release_version" ]; then
  echo "Fetched mismatched last pxc release version"
  echo "bosh.io release version: $bosh_release_version"
  echo "github release version: $github_release_version"
  echo
  echo "This may mean that the release was tagged on github but not promoted as a github release"
  exit 1
fi
