#!/usr/bin/env bash

set -eux

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ci_dir="$( cd ${my_dir}/../.. && pwd )"
workspace_dir="$( cd "${my_dir}/../../../" && pwd )"

source ${ci_dir}/scripts/utils.sh
credhub_login

# optional
: "${CONFIG_LOCATION:=${ci_dir}/integration-config.json}"

env_name=$(cat "${workspace_dir}/environment/name")
domain="$(bosh int "${workspace_dir}/environment/metadata" --path /domain)"

small_plan_size=10
small_plan_name=10mb
large_plan_size=20
large_plan_name=20mb

dashboard_urls="[\"https://0-proxy-p-mysql.${domain}\", \"https://1-proxy-p-mysql.${domain}\"]"

cat > ${CONFIG_LOCATION} <<EOF
{
  "api": "https://api.${domain}",
  "apps_domain": "${domain}",
  "admin_user": "admin",
  "admin_password": "$(cf_admin_password)",
  "broker_host": "p-mysql.${domain}",
  "service_name": "p-mysql",
  "plans" : [
    {
      "name": "${small_plan_name}",
      "max_user_connections": 20,
      "max_storage_mb": ${small_plan_size}
    },
    {
      "name": "${large_plan_name}",
      "max_user_connections": 40,
      "max_storage_mb": ${large_plan_size}
    }
  ],
  "skip_ssl_validation": true,
  "timeout_scale": 1.0,
  "proxy": {
    "dashboard_urls": ${dashboard_urls},
    "api_username": "proxy",
    "api_password": "$(credhub_value cf-mysql/cf_mysql_proxy_api_password)",
    "api_force_https": true,
    "skip_ssl_validation": true
  }
}
EOF
