#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd ${MY_DIR}/../../ && pwd )"
WORKSPACE_DIR="$( cd ${CI_DIR}/../ && pwd )"
source ${CI_DIR}/scripts/utils.sh

ENV_VARS_FROM_LOCK=$(read_vars_from_env_lock_file $ENV_LOCK_FILE)
echo $ENV_VARS_FROM_LOCK > /tmp/env_vars_from_lock
source /tmp/env_vars_from_lock
rm /tmp/env_vars_from_lock

echo "ENV: ${ENV:?}"

bosh -n target bosh.${ENV}.cf-app.com

echo "DEPLOYMENT_NAME: ${DEPLOYMENT_NAME:?}"

set +e
check_if_deployment_exists ${DEPLOYMENT_NAME}
DEPLOYMENT_GREP_RESULT=$?
set -e

# A value of 0 indicates grep matched successfully,
# and hence the deployment exists
if [ ${DEPLOYMENT_GREP_RESULT} -eq 0 ]; then
  bosh -n delete deployment ${DEPLOYMENT_NAME} --force
else
  echo "deployment ${DEPLOYMENT_NAME} not found - nothing to delete"
fi