#!/bin/bash

set -eux -o pipefail

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd "${MY_DIR}/../.." && pwd )"
WORKSPACE_DIR="$( cd "${CI_DIR}/.." && pwd )"
RELEASE_DIR="$( cd "${WORKSPACE_DIR}/cf-mysql-release" && pwd )"

source "${CI_DIR}/scripts/utils.sh"

: "${ENV_TARGET_FILE:?}"
: "${ENV_METADATA:?}"
: "${DEPLOYMENTS_DIR:?}"
: "${RUN_ALL_ACCEPTANCE_TESTS:=false}"
: "${USE_EXISTING_CF_MANIFEST:=false}"

# ensure DEPLOYMENTS_DIR is an absolute path
if [[ "${DEPLOYMENTS_DIR}" != /* ]]; then
  DEPLOYMENTS_DIR="${WORKSPACE_DIR}/${DEPLOYMENTS_DIR}"
fi

BOSH_TARGET="$(cat "${ENV_TARGET_FILE}")"
ENV="$(jq_val "env" "${ENV_METADATA}")"
BOSH_USER="$(jq_val "bosh_user" "${ENV_METADATA}")"
BOSH_PASSWORD="$(jq_val "bosh_password" "${ENV_METADATA}")"

bosh -n target "${BOSH_TARGET}"
bosh -n login "${BOSH_USER}" "${BOSH_PASSWORD}"

echo "args: $*"

tmpdir=$(mktemp -d /tmp/mysql_manifest.XXXXX)
trap '{ rm -rf ${tmpdir}; }' EXIT

PROPERTY_OVERRIDES="${DEPLOYMENTS_DIR}/${ENV}/stubs/mysql/property_overrides.yml" 
if [[ "${RUN_ALL_ACCEPTANCE_TESTS}" = "true" ]]; then
  CUSTOM_STUB="${tmpdir}/cf-mysql-acceptance-tests-stub.yml"
  cat > ${CUSTOM_STUB} <<EOF
---
property_overrides:
  acceptance_tests:
    smoke_tests_only: false
EOF

  spiff merge "${PROPERTY_OVERRIDES}" \
    "${CUSTOM_STUB}" \
    > "${tmpdir}/custom_property_overrides.yml"

  PROPERTY_OVERRIDES="${tmpdir}/custom_property_overrides.yml"
fi

if [ "${USE_EXISTING_CF_MANIFEST}" = false ]; then
  bosh download manifest cf "${tmpdir}/cf-manifest.yml"
  CF_MANIFEST=${tmpdir}/cf-manifest.yml
else
  CF_MANIFEST="${DEPLOYMENTS_DIR}/${ENV}/stubs/cf/cf-manifest.yml"
fi

pushd ${RELEASE_DIR}
  ./scripts/generate-deployment-manifest \
    -c "${CF_MANIFEST}" \
    -i "${DEPLOYMENTS_DIR}/${ENV}/stubs/mysql/aws_iaas_settings.yml" \
    -p "${PROPERTY_OVERRIDES}" \
    -n "${DEPLOYMENTS_DIR}/${ENV}/stubs/mysql/instance_count_overrides.yml" \
    > deployment.yml
  cp deployment.yml ${WORKSPACE_DIR}/deployment-manifest/deployment.yml 
  # Leaving a copy in the workspace dir so that a task can expose it as an output
  bosh deployment deployment.yml
  cat deployment.yml
popd

echo "Manifest generated successfully"
