#!/bin/bash

set -eux -o pipefail

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd "${MY_DIR}/../.." && pwd )"
WORKSPACE_DIR="$( cd "${CI_DIR}/.." && pwd )"
RELEASE_DIR="$( cd "${WORKSPACE_DIR}/cf-mysql-release" && pwd )"
MANIFEST_DIR="${WORKSPACE_DIR}/${MANIFEST_DIR:-deployment-manifest}"

source "${CI_DIR}/scripts/utils.sh"

: "${ENV_TARGET_FILE:?}"
: "${ENV_METADATA:?}"
: "${DEPLOYMENTS_DIR:?}"
: "${RUN_ALL_ACCEPTANCE_TESTS:=false}"
: "${USE_EXISTING_CF_MANIFEST:=false}"
: "${CAT_MANIFEST:=true}"
: "${CF_DEPLOYMENT_NAME:=cf}"

# ensure DEPLOYMENTS_DIR is an absolute path
if [[ "${DEPLOYMENTS_DIR}" != /* ]]; then
  DEPLOYMENTS_DIR="${WORKSPACE_DIR}/${DEPLOYMENTS_DIR}"
fi

BOSH_TARGET="$(cat "${ENV_TARGET_FILE}")"
ENV="$(jq_val "env" "${ENV_METADATA}")"
BOSH_CLIENT="$(jq_val "bosh_user" "${ENV_METADATA}")"
BOSH_PASSWORD="$(jq_val "bosh_password" "${ENV_METADATA}")"


: "${PROPERTY_OVERRIDES_FILE:=${ENV}/stubs/mysql/property_overrides.yml}"
: "${IAAS_SETTINGS_FILE:=${ENV}/stubs/mysql/aws_iaas_settings.yml}"
: "${INSTANCE_COUNT_OVERRIDES_FILE:=${ENV}/stubs/mysql/instance_count_overrides.yml}"
: "${JOB_OVERRIDES_FILE:=}"

if [[ ! -z "${JOB_OVERRIDES_FILE}" ]]; then
  JOB_OVERRIDES_FILE="${DEPLOYMENTS_DIR}/${JOB_OVERRIDES_FILE}"
fi
IAAS_SETTINGS_FILE="${DEPLOYMENTS_DIR}/${IAAS_SETTINGS_FILE}"
INSTANCE_COUNT_OVERRIDES_FILE="${DEPLOYMENTS_DIR}/${INSTANCE_COUNT_OVERRIDES_FILE}"
PROPERTY_OVERRIDES_FILE="${DEPLOYMENTS_DIR}/${PROPERTY_OVERRIDES_FILE}"
CF_MANIFEST="${DEPLOYMENTS_DIR}/${ENV}/stubs/cf/cf-manifest.yml"

bosh -n target "${BOSH_TARGET}"
bosh -n login "${BOSH_CLIENT}" "${BOSH_PASSWORD}"

echo "args: $*"

tmpdir=$(mktemp -d /tmp/mysql_manifest.XXXXX)
trap '{ rm -rf ${tmpdir}; }' EXIT

if [[ "${RUN_ALL_ACCEPTANCE_TESTS}" = "true" ]]; then
  CUSTOM_STUB="${tmpdir}/cf-mysql-acceptance-tests-stub.yml"
  cat > ${CUSTOM_STUB} <<EOF
---
property_overrides:
  acceptance_tests:
    smoke_tests_only: false
EOF

  spiff merge "${PROPERTY_OVERRIDES_FILE}" \
    "${CUSTOM_STUB}" \
    > "${tmpdir}/custom_property_overrides.yml"

  PROPERTY_OVERRIDES_FILE="${tmpdir}/custom_property_overrides.yml"
fi

if [ "${USE_EXISTING_CF_MANIFEST}" = false ]; then
  bosh download manifest "${CF_DEPLOYMENT_NAME}" "${tmpdir}/cf-manifest.yml"
  CF_MANIFEST=${tmpdir}/cf-manifest.yml
fi

pushd ${RELEASE_DIR}
  ./scripts/generate-deployment-manifest \
    -c "${CF_MANIFEST}" \
    -i "${IAAS_SETTINGS_FILE}" \
    -p "${PROPERTY_OVERRIDES_FILE}" \
    -n "${INSTANCE_COUNT_OVERRIDES_FILE}" \
    -j "${JOB_OVERRIDES_FILE}" \
    > deployment.yml
  cp deployment.yml ${MANIFEST_DIR}/deployment.yml
  # Leaving a copy in the workspace dir so that a task can expose it as an output
  bosh deployment deployment.yml
  if [ ${CAT_MANIFEST} = true ]; then
    cat deployment.yml
  fi
popd

echo "Manifest generated successfully"
