#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd "${MY_DIR}/../.." && pwd )"
WORKSPACE_DIR="$( cd "${CI_DIR}/.." && pwd )"
MANIFEST_DIR="${WORKSPACE_DIR}/deployment-manifest"
OUTPUT_FILE="${MANIFEST_DIR}/deployment.yml"

source "${CI_DIR}/scripts/utils.sh"

: "${ENV_NAME:?}"
: "${DEPLOYMENTS_DIR:?}"

# ensure DEPLOYMENTS_DIR is an absolute path
if [[ "${DEPLOYMENTS_DIR}" != /* ]]; then
  DEPLOYMENTS_DIR="${WORKSPACE_DIR}/${DEPLOYMENTS_DIR}"
fi

ENV_DIR="${DEPLOYMENTS_DIR}/${ENV_NAME}/"

bosh interpolate \
    --vars-file=${ENV_DIR}/vars.yml \
    ${WORKSPACE_DIR}/cf-mysql-deployment/cf-mysql-deployment.yml \
    -o ${WORKSPACE_DIR}/cf-mysql-deployment/operations/add-broker.yml \
    -o ${WORKSPACE_DIR}/cf-mysql-deployment/operations/register-proxy-route.yml \
    -o ${WORKSPACE_DIR}/cf-mysql-deployment/operations/disable-smoke-tests-cross-deployment-links.yml \
    -o ${WORKSPACE_DIR}/cf-mysql-deployment/operations/disable-broker-route-registrar-cross-deployment-links.yml \
    -o ${WORKSPACE_DIR}/cf-mysql-deployment/operations/disable-proxy-route-registrar-cross-deployment-links.yml \
    -o ${WORKSPACE_DIR}/cf-mysql-deployment/operations/no-arbitrator.yml \
    -o ${WORKSPACE_DIR}/cf-mysql-deployment/operations/proxy-elb.yml \
    -o ${ENV_DIR}/infrastructure.yml \
    -o ${ENV_DIR}/service-broker.yml \
    > "${OUTPUT_FILE}"
