#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd "${MY_DIR}/../.." && pwd )"
WORKSPACE_DIR="$( cd "${CI_DIR}/.." && pwd )"
MANIFEST_DIR="${WORKSPACE_DIR}/deployment-manifest"
OUTPUT_FILE="${MANIFEST_DIR}/deployment.yml"

source "${CI_DIR}/scripts/utils.sh"

: "${ENV_METADATA:?}"
: "${DEPLOYMENTS_DIR:?}"

# ensure DEPLOYMENTS_DIR is an absolute path
if [[ "${DEPLOYMENTS_DIR}" != /* ]]; then
  DEPLOYMENTS_DIR="${WORKSPACE_DIR}/${DEPLOYMENTS_DIR}"
fi

ENV="$(jq_val "env" "${ENV_METADATA}")"
VARS_FILE="${DEPLOYMENTS_DIR}/${ENV}/stubs/mysql/vars.yml"

gobosh interpolate \
    ./cf-mysql-deployment/cf-mysql-deployment.yml \
    -o ./cf-mysql-deployment/operations/latest-versions.yml \
    -o ./cf-mysql-deployment/operations/add-broker.yml \
    -o ./cf-mysql-deployment/operations/register-proxy-route.yml \
    -o ./cf-mysql-deployment/operations/disable-cross-deployment-links.yml \
    -l ${VARS_FILE} \
    > "${OUTPUT_FILE}"
