#!/bin/bash

set -eux -o pipefail

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd "${MY_DIR}/../.." && pwd )"
WORKSPACE_DIR="$( cd "${CI_DIR}/.." && pwd )"
RELEASE_DIR="$( cd "${WORKSPACE_DIR}/cf-mysql-release" && pwd )"

source "${CI_DIR}/scripts/utils.sh"

: "${ENV_TARGET_FILE:?}"
: "${ENV_METADATA:?}"
: "${DEPLOYMENTS_DIR:?}"
: "${RUN_ALL_ACCEPTANCE_TESTS:=false}"

# ensure DEPLOYMENTS_DIR is an absolute path
if [[ "${DEPLOYMENTS_DIR}" != /* ]]; then
  DEPLOYMENTS_DIR="${WORKSPACE_DIR}/${DEPLOYMENTS_DIR}"
fi

BOSH_TARGET="$(cat "${ENV_TARGET_FILE}")"
ENV="$(jq_val "env" "${ENV_METADATA}")"
BOSH_USER="$(jq_val "bosh_user" "${ENV_METADATA}")"
BOSH_PASSWORD="$(jq_val "bosh_password" "${ENV_METADATA}")"

bosh -n target "${BOSH_TARGET}"
bosh -n login "${BOSH_USER}" "${BOSH_PASSWORD}"

echo "args: $*"

CUSTOM_STUB=/tmp/cf-mysql-acceptance-tests-stub.yml
rm -f ${CUSTOM_STUB} && touch ${CUSTOM_STUB}
if [[ "${RUN_ALL_ACCEPTANCE_TESTS}" = "true" ]]; then
  cat > ${CUSTOM_STUB} <<EOF
---
jobs:
- name: acceptance-tests
  properties:
    smoke_tests_only: false
EOF
fi

pushd ${RELEASE_DIR}
  ./generate_deployment_manifest \
    aws \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/cf/cf-aws-stub.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/cf/cf-networks-stub.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/cf/cf-shared-secrets.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/mysql/cf-mysql-plans-stub.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/cf/cf-properties.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/mysql/cf-mysql-secrets.yml \
    "$@" > deployment.yml

  bosh deployment deployment.yml
  cat deployment.yml
popd

echo "Manifest generated successfully"
