#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd ${MY_DIR}/../../ && pwd )"
WORKSPACE_DIR="$( cd ${CI_DIR}/../ && pwd )"
source ${CI_DIR}/scripts/utils.sh

ENV_VARS_FROM_LOCK=$(read_vars_from_env_lock_file $ENV_LOCK_FILE)
echo $ENV_VARS_FROM_LOCK > /tmp/env_vars_from_lock
source /tmp/env_vars_from_lock
rm /tmp/env_vars_from_lock

SKIP_IF_NO_DEPLOYMENT="${SKIP_IF_NO_DEPLOYMENT:-false}"
ERRAND="${ERRAND:?}"

bosh -n target "bosh.${ENV}.cf-app.com"

set +e
check_if_deployment_exists ${DEPLOYMENT_NAME}
DEPLOYMENT_GREP_RESULT=$?
set -e

# A value of 0 indicates deployment exists
if [ ${DEPLOYMENT_GREP_RESULT} -ne 0 ]; then
  if [ "${SKIP_IF_NO_DEPLOYMENT}" = "true" ]; then
    echo "deployment ${DEPLOYMENT_NAME} does not exist, skipping errand"
    exit 0
  else
    echo "deployment ${DEPLOYMENT_NAME} does not exist"
    exit 1
  fi
fi

MANIFEST_FILE=/tmp/errand-manifest.yml
bosh download manifest ${DEPLOYMENT_NAME} ${MANIFEST_FILE}
bosh deployment ${MANIFEST_FILE}
bosh run errand ${ERRAND}