#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd ${MY_DIR}/../.. && pwd )"

OK_COLOR='\033[1;32m'
ACTION_COLOR='\033[1;33m'
INFO_COLOR='\033[1;36m'
NO_COLOR='\033[0m'

BOSH_LITE_METADATA="${BOSH_LITE_METADATA:-}"
if [ ! -z "${BOSH_LITE_METADATA}" ]; then
  DOMAIN=$(cat "${BOSH_LITE_METADATA}" | jq -r '.domain' )
  CF_API_PASSWORD=$(cat "${BOSH_LITE_METADATA}" | jq -r '.cf_password' )
fi
export DOMAIN="${DOMAIN:-bosh-lite.com}"
export CF_API_PASSWORD="${CF_API_PASSWORD:-admin}"

export CF_API_USER="admin"
export PROXY_API_USER="username"
export PROXY_API_PASSWORD="password"
export USE_SMALL_PLANS=true
export USE_HTTPS=false

${CI_DIR}/scripts/bosh/create_integration_test_config
