#!/usr/bin/env bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="$( cd "${MY_DIR}/../../../" && pwd )"

DIRECTOR_IP_FILE="${DIRECTOR_IP_FILE:?}"
BOSH_PASSWORD_FILE="${BOSH_PASSWORD_FILE:?}"
export BOSH_USER=${BOSH_USER:?}

# ensure DEPLOYMENTS_DIR is an absolute path
DEPLOYMENTS_DIR="${DEPLOYMENTS_DIR:?}"
if [[ "${DEPLOYMENTS_DIR}" != /* ]]; then
  DEPLOYMENTS_DIR="${WORKSPACE_DIR}/${DEPLOYMENTS_DIR}"
fi

source ${DEPLOYMENTS_DIR}/scripts/utils.sh

pushd ${WORKSPACE_DIR}
  DIRECTOR_IP=$(cat ${DIRECTOR_IP_FILE})
  BOSH_PASSWORD=$(cat ${BOSH_PASSWORD_FILE} | jq -r '.director_password')
  export BOSH_PASSWORD
popd

bosh -n target "${DIRECTOR_IP}"

echo "DEPLOYMENT_NAME: ${DEPLOYMENT_NAME:?}"

set +e
check_if_deployment_exists ${DEPLOYMENT_NAME}
DEPLOYMENT_GREP_RESULT=$?
set -e

# A value of 0 indicates grep matched successfully,
# and hence the deployment exists
if [ "${DEPLOYMENT_GREP_RESULT}" -eq 0 ]; then
  bosh -n delete deployment ${DEPLOYMENT_NAME} --force
else
  echo "deployment ${DEPLOYMENT_NAME} not found - nothing to delete"
fi
