#!/bin/bash

set -eux

: "${DNS_NAME}"
: "${PROXY_LB:=false}"
: "${DEPLOY_WITH_BOSH_DNS:=false}"

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
workspace_dir="$( cd "${my_dir}/../../../" && pwd )"

operations=""

if ${DEPLOY_WITH_DIEGO_CA_CERT}; then
    operations="$operations -o ${workspace_dir}/cf-mysql-ci/operations/add-trusted-cert-for-apps-variable.yml"
    operations="$operations -o ${workspace_dir}/cf-deployment/operations/use-trusted-ca-cert-for-apps.yml"
fi

if ${REMOTE_ADMIN_ACCESS}; then
    operations="$operations -o ${workspace_dir}/cf-mysql-ci/operations/cf-deployment/enable-remote-admin-access-cf-mysql.yml"
fi

if ${PROXY_LB}; then
    operations="$operations -v vm_extension=mysql-proxy-lb"
    operations="$operations -o ./cf-mysql-ci/operations/cf-deployment/add-database-vm-extension.yml"
fi

if ${DEPLOY_WITH_BOSH_DNS}; then
    operations="$operations -o ./cf-deployment/operations/use-bosh-dns.yml"
fi

bosh int \
    ${workspace_dir}/cf-deployment/cf-deployment.yml \
    --vars-store ${workspace_dir}/varstore/deployment-vars.yml \
    -o ${workspace_dir}/cf-deployment/operations/use-compiled-releases.yml \
    -o ${workspace_dir}/cf-deployment/operations/bosh-lite.yml \
    -o ${workspace_dir}/cf-mysql-ci/operations/cf-allow-apps-access-to-mysql.yml \
    -o ${workspace_dir}/cf-mysql-ci/operations/cf-deployment/increase-proxy-healthcheck-timeout.yml \
    ${operations} \
    -v system_domain="$(cat "$DNS_NAME")" \
    > "${OUTPUT_FILE}"
