#!/bin/bash

set -eux

: "${MINIMAL_MODE:=false}"
: "${DISABLE_INTERRUPTOR:=false}"
: "${NO_ARBITRATOR:=false}"
: "${TINY_GCACHE:=false}"
: "${ENABLE_REMOTE_ADMIN_ACCESS:=false}"

operations=""

if ${MINIMAL_MODE}; then
    operations="$operations -o ./cf-mysql-ci/operations/minimal-mode.yml"
fi

if ${DISABLE_INTERRUPTOR}; then
    operations="$operations -o ./cf-mysql-ci/operations/disable-interruptor.yml"
fi

if ${NO_ARBITRATOR}; then
    operations="$operations -o ./cf-mysql-deployment/operations/no-arbitrator.yml"
fi

if ${TINY_GCACHE}; then
    operations="$operations -o ./cf-mysql-ci/operations/tiny-gcache.yml"
fi

if ${ENABLE_REMOTE_ADMIN_ACCESS}; then
    operations="$operations -o ./cf-mysql-ci/operations/enable-remote-admin-access.yml"
fi

gobosh interpolate \
    ./cf-mysql-deployment/cf-mysql-deployment.yml \
    -o ./cf-mysql-deployment/operations/latest-versions.yml \
    ${operations} \
    -o ./cf-mysql-ci/operations/default-vcap-password.yml \
    -l ./cf-mysql-deployment/bosh-lite/default-vars.yml \
    > "${OUTPUT_FILE}"
