#!/bin/bash

set -eux

: "${PROXY_LB:=false}"

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
workspace_dir="$( cd "${my_dir}/../../../" && pwd )"
cd ${workspace_dir}

extras=""

if ${PROXY_LB}; then
    extras="$extras -v vm_extension=mysql-proxy-lb"
    extras="$extras -o ./cf-mysql-ci/operations/cf-deployment/add-database-vm-extension.yml"
fi

bosh int \
    ./cf-deployment/cf-deployment.yml \
    --vars-store ./varstore/deployment-vars.yml \
    -o ./cf-deployment/operations/use-compiled-releases.yml \
    -o ./cf-deployment/operations/bosh-lite.yml \
    -o ./pxc-release/operations/migrate-cf-deployment-to-pxc.yml \
    -o ./pxc-release/operations/use-latest-pxc.yml \
    -o ./cf-mysql-ci/operations/cf-deployment/enable-remote-admin-access.yml \
    -o ${workspace_dir}/cf-mysql-ci/operations/cf-allow-apps-access-to-mysql.yml \
    ${extras} \
    -v system_domain="$(cat "./url/url")" \
    > ./cf-deployment-migrated-manifest/cf.yml
