#!/bin/bash

set -eux

: "${MINIMAL_MODE:=false}"
: "${DISABLE_INTERRUPTOR:=false}"
: "${NO_ARBITRATOR:=false}"
: "${TINY_GCACHE:=false}"

overrides=""

if ${MINIMAL_MODE}; then
    overrides="$overrides -o ./cf-mysql-deployment/manifest-generation/bosh2.0/overrides/minimal-mode.yml"
fi

if ${DISABLE_INTERRUPTOR}; then
    overrides="$overrides -o ./cf-mysql-deployment/manifest-generation/bosh2.0/overrides/disable-interruptor.yml"
fi

if ${NO_ARBITRATOR}; then
    overrides="$overrides -o ./cf-mysql-deployment/manifest-generation/bosh2.0/overrides/no-arbitrator.yml"
fi

if ${TINY_GCACHE}; then
    overrides="$overrides -o ./cf-mysql-ci/overrides/tiny-gcache.yml"
fi

gobosh interpolate \
    ./cf-mysql-deployment/cf-mysql-deployment.yml \
    ${overrides} \
    -l ./cf-mysql-deployment/bosh-lite/default-vars.yml \
    > "${OUTPUT_FILE}"
