#!/bin/bash

set -eux

: "${DNS_NAME}"

# : "${PRECOMPILED_RELEASES:=true}"

# operations=""

# if ${PRECOMPILED_RELEASES}; then
#     operations="$operations -o ./*cf deployment repo here*"
# fi

bosh2 int \
    ~/workspace/cf-deployment/cf-deployment.yml \
    --vars-store ~/workspace/cf-deployment/deployment-vars.yml \
    $operations \
    -o ~/workspace/cf-deployment/operations/bosh-lite.yml \
    -v system_domain="$DNS_NAME" \
    -o local-security-groups.yml
