#!/bin/bash

set -eux

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
workspace_dir="$( cd "${my_dir}/../../../" && pwd )"
cd ${workspace_dir}

bosh int \
    ./cf-deployment/cf-deployment.yml \
    --vars-store ./varstore/deployment-vars.yml \
    -v system_domain="$(cat "./url/url")" \
    -o ./cf-deployment/operations/use-compiled-releases.yml \
    -o ./cf-deployment/operations/bosh-lite.yml \
    -o ./cf-deployment/operations/scale-database-cluster.yml \
    -o ./pxc-release/operations/cf-deployment-use-pxc.yml \
    > ./cf-deployment-manifest/cf.yml
