#!/bin/bash

# TODO: #110903058 This file can be removed after v26 is released

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd ${MY_DIR}/../.. && pwd )"
WORKSPACE_DIR="$( cd ${CI_DIR}/.. && pwd )"
RELEASE_DIR="$( cd ${WORKSPACE_DIR}/cf-mysql-release && pwd )"

source ${CI_DIR}/scripts/utils.sh

: "${OUTPUT_FILE:?}"
: "${ENV_METADATA:?}"
: "${NODE_COUNT:=3}"
: "${USE_PREVIOUS_RELEASE:=false}"
: "${STANDALONE_MODE:=false}"

DOMAIN="$(jq_val "domain" "${ENV_METADATA}")"
CF_ADMIN_PASSWORD="$(jq_val "cf_api_password" "${ENV_METADATA}")"

get_version() {
  if [ "${USE_PREVIOUS_RELEASE}" = true ]; then
  echo "$(find ${RELEASE_DIR}/releases/cf-mysql-* -type f -printf "%f\n" | \
    cut -d '-' -f3              | \
    cut -d '.' -f1              | \
    sort -n                     | \
    tail -1)"
  else
    echo "latest"
  fi
}

# select stub that corresponds to $NODE_COUNT
MYSQL_STUB="${RELEASE_DIR}/bosh-lite/cf-mysql-stub-spiff-${NODE_COUNT}-node.yml"
if [[ ! -f "${MYSQL_STUB}" ]] ; then
  echo "Can't find ${MYSQL_STUB}"
  exit 1
fi

# concourse bosh resource will automatically replace the UUID
MYSQL_STUB_MODIFIED=/tmp/mysql-stub.yml
sed 's/PLACEHOLDER-DIRECTOR-UUID/~/' ${MYSQL_STUB} > ${MYSQL_STUB_MODIFIED}

MYSQL_VERSION="$(get_version)"
CUSTOM_CI_STUB=/tmp/custom-mysql-ci-stub.yml
cat <<CI_STUB > ${CUSTOM_CI_STUB}
releases:
- name: cf-mysql
  version: ${MYSQL_VERSION}
properties:
  domain: ${DOMAIN}
  system_domain: ${DOMAIN}
  app_domains:
  - ${DOMAIN}
  cf:
    admin_password: ${CF_ADMIN_PASSWORD}
CI_STUB

STANDALONE_STUB=""
if [ "${STANDALONE_MODE}" = true ] ; then
  STANDALONE_STUB="${RELEASE_DIR}/bosh-lite/cf-mysql-standalone-stub.yml"
fi

${RELEASE_DIR}/generate_deployment_manifest \
  warden \
  ${RELEASE_DIR}/templates/sample_stubs/sample_plans_stub.yml \
  ${MYSQL_STUB_MODIFIED} \
  ${CUSTOM_CI_STUB} \
  ${STANDALONE_STUB} \
  "$@" > ${WORKSPACE_DIR}/${OUTPUT_FILE}
