#!/bin/bash

set -eux


my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
workspace_dir="$( cd "${my_dir}/../../../" && pwd )"
cd ${workspace_dir}

bosh int \
    ./pxc-release/pxc-deployment.yml \
    --vars-store ./varstore/deployment-vars.yml \
    -o ./pxc-release/operations/use-clustered.yml \
    -o ./cf-mysql-ci/operations/pxc/add-proxy-load-balancer.yml \
    -o ./cf-mysql-ci/operations/pxc/allow-http-proxy-access.yml \
    -o ./cf-mysql-ci/operations/pxc/enable-remote-admin-access.yml \
    > ./pxc-manifest/pxc.yml
