#!/bin/bash

set -eux

: "${DNS_NAME}"

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
workspace_dir="$( cd "${my_dir}/../../../" && pwd )"

operations=""

if ${DEPLOY_WITH_DIEGO_CA_CERT}; then
    operations="$operations -o ${workspace_dir}/cf-mysql-ci/operations/add-trusted-cert-for-apps-variable.yml"
    operations="$operations -o ${workspace_dir}/cf-deployment/operations/use-trusted-ca-cert-for-apps.yml"
fi

bosh int \
    ${workspace_dir}/cf-deployment/cf-deployment.yml \
    --vars-store ${workspace_dir}/varstore/deployment-vars.yml \
    -o ${workspace_dir}/cf-deployment/operations/use-compiled-releases.yml \
    -o ${workspace_dir}/cf-deployment/operations/bosh-lite.yml \
    -v system_domain="$(cat "$DNS_NAME")" \
    -o ${workspace_dir}/cf-mysql-ci/operations/cf-allow-apps-access-to-mysql.yml \
    ${operations} \
    > "${OUTPUT_FILE}"
