#!/bin/bash

set -eux

: "${MINIMAL_MODE:=false}"
: "${DISABLE_INTERRUPTOR:=false}"
: "${NO_ARBITRATOR:=false}"
: "${TINY_GCACHE:=false}"
: "${ENABLE_REMOTE_ADMIN_ACCESS:=false}"
: "${TUNE_BY_EXACT_SIZE:=false}"
: "${TUNE_BY_PERCENTAGE:=false}"
: "${ADD_BROKERS:=false}"
: "${DISABLE_CROSS_DEPLOYMENT_LINKS:=true}"
: "${EVERYTHING_ENABLED:=false}"
: "${EVERYTHING_DISABLED:=false}"
: "${STATIC_PROXY_IPS:=false}"
: "${VARS_FILE:=}"

VARS_FILE_OPTION=''
if [[ ! -z "${VARS_FILE}" ]]; then
  VARS_FILE_OPTION="-l ${VARS_FILE}"
fi

operations=""
variables=""

if ${MINIMAL_MODE}; then
    operations="$operations -o ./cf-mysql-ci/operations/minimal-mode.yml"
fi

if ${DISABLE_INTERRUPTOR}; then
    operations="$operations -o ./cf-mysql-ci/operations/disable-interruptor.yml"
fi

if ${NO_ARBITRATOR}; then
    operations="$operations -o ./cf-mysql-deployment/operations/no-arbitrator.yml"
fi

if ${TINY_GCACHE}; then
    operations="$operations -o ./cf-mysql-ci/operations/tiny-gcache.yml"
fi

if ${ENABLE_REMOTE_ADMIN_ACCESS}; then
    operations="$operations -o ./cf-mysql-ci/operations/enable-remote-admin-access.yml"
fi

if ${TUNE_BY_EXACT_SIZE}; then
    operations="$operations -o ./cf-mysql-ci/operations/tune-buffer-by-exact-size.yml"
fi

if ${TUNE_BY_PERCENTAGE}; then
    operations="$operations -o ./cf-mysql-ci/operations/tune-buffer-by-percentage.yml"
fi

if ${EVERYTHING_ENABLED}; then
    operations="$operations -o ./cf-mysql-release/src/github.com/cloudfoundry-incubator/cf-mysql-acceptance-tests/assets/tuning/everything_enabled.yml"
fi

if ${EVERYTHING_DISABLED}; then
    operations="$operations -o ./cf-mysql-release/src/github.com/cloudfoundry-incubator/cf-mysql-acceptance-tests/assets/tuning/everything_disabled.yml"
fi

if ${ADD_BROKERS}; then
    operations="$operations -o ./cf-mysql-deployment/operations/add-broker.yml"
    operations="$operations -o ./cf-mysql-deployment/operations/register-proxy-route.yml"
    operations="$operations -o ./cf-mysql-ci/operations/add-proxy-and-broker-load-balancers.yml"
    operations="$operations -o ./cf-mysql-ci/operations/default-vcap-password-broker.yml"
    if ${DISABLE_CROSS_DEPLOYMENT_LINKS}; then
        operations="$operations -o ./cf-mysql-deployment/operations/disable-cross-deployment-links.yml"
    fi
    cf_url="$(cat url/url)"
    cf_admin_password="$(bosh int varstore/deployment-vars.yml --path=/cf_admin_password)"
    variables="$variables \
    -v cf_admin_username=admin \
    -v cf_admin_password=\"${cf_admin_password}\" \
    -v cf_api_url=\"https://api.${cf_url}\" \
    -v app_domains=[${cf_url}] \
    -v cf_mysql_external_host=\"p-mysql.${cf_url}\""
fi

if ${STATIC_PROXY_IPS}; then
    operations="$operations -o ./cf-mysql-ci/operations/static-proxy-ips.yml"
fi

bosh interpolate \
    ./cf-mysql-deployment/cf-mysql-deployment.yml \
    -o ./cf-mysql-deployment/operations/latest-versions.yml \
    ${operations} \
    -o ./cf-mysql-ci/operations/default-vcap-password.yml \
    -l ./cf-mysql-deployment/bosh-lite/default-vars.yml \
    ${VARS_FILE_OPTION} \
    ${variables} \
    > "${OUTPUT_FILE}"
