#!/bin/bash -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="$( cd ${MY_DIR}/../../.. && pwd )"
RELEASE_DIR="${WORKSPACE_DIR}/cf-mysql-release"

function main() {
  local root_dir
  root_dir="${1}"

  local protocol
  protocol="${2}"

  local total
  total="$(count_with_protocol "${root_dir}" "")"

  local with_protocol
  with_protocol="$(count_with_protocol "${root_dir}" "${protocol}")"

  if [ "${total}" != "${with_protocol}" ]; then
    echo "found git submodules not using ${protocol}"
    grep "url = " "${root_dir}/.gitmodules" | grep -v "url = ${protocol}://"
    exit 1
  else
    echo "all submodules use ${protocol}, I'm happy"
    exit 0
  fi
}

function count_with_protocol() {
  local repo
  repo="${1}"

  local protocol
  protocol="${2}"

  if [[ -n "${protocol}" ]]; then
    protocol="${protocol}://"
  fi

  printf "%s" "$(grep "url = ${protocol}" "${repo}/.gitmodules" | wc -l)"
}

pushd ${RELEASE_DIR}
  main "${PWD}" "https"
popd
