#!/bin/bash
set -eux

# DEPRECATED
# This is being replaced with restart-broken-node in the bosh2/ondemand world

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd ${MY_DIR}/../../ && pwd )"
WORKSPACE_DIR="$( cd ${MY_DIR}/../../.. && pwd )"

: "${BOSH_SSH_KEY:?}"
: "${ENV_TARGET_FILE:?}"
: "${ENV_METADATA:?}"
: "${DEPLOYMENT_MANIFEST:?}"

source ${CI_DIR}/scripts/utils.sh

director_ip="$(cat "${ENV_TARGET_FILE}")"
export BOSH_ENVIRONMENT="$(sslip_from_ip "${director_ip}")"
export BOSH_CLIENT="$(jq_val "bosh_user" "${ENV_METADATA}")"
export BOSH_CLIENT_SECRET="$(jq_val "bosh_password" "${ENV_METADATA}")"

function start_mysql_z2_0() {
  bosh -n start mysql_z2/0
}

start_mysql_z2_0
