#!/bin/bash
set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd ${MY_DIR}/../../ && pwd )"
WORKSPACE_DIR="$( cd ${MY_DIR}/../../.. && pwd )"

: "${BOSH_SSH_KEY:?}"
: "${ENV_TARGET_FILE:?}"
: "${ENV_METADATA:?}"
: "${DEPLOYMENT_MANIFEST:?}"

source ${CI_DIR}/scripts/utils.sh

BOSH_TARGET="$(cat "${ENV_TARGET_FILE}")"
ENV="$(jq_val "env" "${ENV_METADATA}")"
BOSH_CLIENT="$(jq_val "bosh_user" "${ENV_METADATA}")"
BOSH_CLIENT_SECRET="$(jq_val "bosh_password" "${ENV_METADATA}")"

function start_mysql_z2_0() {
  bosh -n target "${BOSH_TARGET}"
  bosh -n login "${BOSH_CLIENT}" "${BOSH_CLIENT_SECRET}"
  bosh deployment ${DEPLOYMENT_MANIFEST}
  bosh -n start mysql_z2 0 --force
}

start_mysql_z2_0
