#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd "${MY_DIR}/../../" && pwd )"
WORKSPACE_DIR="$( cd "${MY_DIR}/../../../" && pwd )"
RELEASE_DIR="$(cd "${WORKSPACE_DIR}/cf-mysql-release" && pwd )"
source ${CI_DIR}/scripts/utils.sh

ENV_VARS_FROM_LOCK=$(read_vars_from_env_lock_file $ENV_LOCK_FILE)
echo $ENV_VARS_FROM_LOCK > /tmp/env_vars_from_lock
source /tmp/env_vars_from_lock
rm /tmp/env_vars_from_lock

export PATH=$PATH:/usr/lib/chromium-browser/
export LD_LIBRARY_PATH=/usr/lib/chromium-browser/libs

export CONFIG_LOCATION="${CI_DIR}/integration-config.json"
IS_BOSH_LITE="${IS_BOSH_LITE:-false}"
if [[ "${IS_BOSH_LITE}" = "false" ]]; then
  ${CI_DIR}/scripts/bosh/create_integration_test_config
else
  ${CI_DIR}/scripts/bosh-lite/create_integration_test_config
fi
export CONFIG="${CONFIG_LOCATION}"

source ${RELEASE_DIR}/.envrc

# Remove and reinstall the ginkgo binary as it might be from the wrong target architecture
rm -rf ${RELEASE_DIR}/bin/ginkgo
go install -v github.com/onsi/ginkgo/ginkgo

echo -e "\nTesting Dashboard SSO"
${RELEASE_DIR}/src/github.com/cloudfoundry-incubator/cf-mysql-acceptance-tests/bin/test-dashboard "$@"