#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="${MY_DIR}/../../../"
RELEASE_DIR="${WORKSPACE_DIR}/pxc-release"

export BOSH_ENVIRONMENT=$(cat bosh-lite-info/external-ip)
export BOSH_CA_CERT="$(cat "${BOSH_CA_CERT_PATH}")"
export MYSQL_USERNAME=root
export MYSQL_PASSWORD=$(bosh int varstore/pxc-deployment-vars.yml --path /cf_mysql_mysql_admin_password)
export PROXY_USERNAME=proxy
export PROXY_PASSWORD=$(bosh int varstore/pxc-deployment-vars.yml --path /cf_mysql_proxy_api_password)

bosh update-resurrection off
# turn off the resurrector so that `scan-and-fix` tasks don't collide with our tests

source ${RELEASE_DIR}/.envrc # To set GOPATH to release dir
pushd ${RELEASE_DIR}/src/specs/integration
  echo "Running tests ..."
  ginkgo failover
popd
