#!/bin/bash

set -eux

pushd ${ENV_DIR}
  source .envrc
popd

ca_cert=$(cat ${ENV_DIR}/${BOSH_CA_CERT} | awk '{printf "%s\\n", $0}')

cat << EOF > ${OUTPUT_FILE}
{
    "target": "${BOSH_ENVIRONMENT}",
    "client": "${BOSH_CLIENT}",
    "client_secret": "${BOSH_CLIENT_SECRET}",
    "ca_cert": "${ca_cert}"
}
EOF
