#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd ${MY_DIR}/../ && pwd )"
WORKSPACE_DIR="$( cd ${MY_DIR}/../.. && pwd )"
RELEASE_DIR="$( cd ${WORKSPACE_DIR}/cf-mysql-release && pwd )"

echo "ENV: ${ENV:?}"

source ${CI_DIR}/scripts/utils.sh

bosh -n target bosh.${ENV}.cf-app.com

echo "args: $*"

pushd ${RELEASE_DIR}
  ./generate_deployment_manifest \
    aws \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-aws-stub.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-networks-stub.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-shared-secrets.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-mysql-plans-stub.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-properties.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/cf-mysql-secrets.yml \
    "$@" > deployment.yml

  bosh deployment deployment.yml
  cat deployment.yml
popd

echo "Manifest generated successfully"
