#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="$( cd ${MY_DIR}/../.. && pwd )"

# ensure DEPLOYMENTS_DIR is an absolute path
DEPLOYMENTS_DIR="${DEPLOYMENTS_DIR:?}"
if [[ "${DEPLOYMENTS_DIR}" != /* ]]; then
  DEPLOYMENTS_DIR="${WORKSPACE_DIR}/${DEPLOYMENTS_DIR}"
fi

echo "ENV: ${ENV:?}"

source ${DEPLOYMENTS_DIR}/utils.sh
source_bosh_environment

echo "DEPLOYMENT_NAME: ${DEPLOYMENT_NAME:?}"
echo "ERRAND: ${ERRAND:?}"

bosh -n target bosh.${ENV}.cf-app.com

set +e
check_if_deployment_exists ${DEPLOYMENT_NAME}
DEPLOYMENT_GREP_RESULT=$?
set -e

# A value of 0 indicates grep matched successfully,
# and hence the deployment exists
if [ ${DEPLOYMENT_GREP_RESULT} -eq 0 ]; then
  MANIFEST=${DEPLOYMENTS_DIR}/deployment.yml
  bosh download manifest ${DEPLOYMENT_NAME} ${MANIFEST}
  bosh deployment ${MANIFEST}
  bosh run errand ${ERRAND}
else
  echo "deployment ${DEPLOYMENT_NAME} not found"
  exit 1
fi
