#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "ENV: ${ENV:?}"

source ${MY_DIR}/utils.sh
source_bosh_environment

bosh -n target bosh.${ENV}.cf-app.com

${MY_DIR}/make_manifest_cf_mysql

echo "Running broker-registrar errand"
bosh run errand broker-registrar
