#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "ENV: ${ENV:?}"

source ${MY_DIR}/utils.sh
source_bosh_environment

bosh -n target bosh.${ENV}.cf-app.com

stub_location=/tmp/cf-mysql-acceptance-tests-stub.yml

cat > ${stub_location} <<EOF
---
jobs:
- name: acceptance-tests
  properties:
    smoke_tests_only: false
EOF

${MY_DIR}/make_manifest_cf_mysql ${stub_location}
rm -rf ${stub_location}

# Redeploy with new errand property
bosh -n deploy

echo "Running acceptance tests"
bosh run errand acceptance-tests
