#!/bin/bash

set -eu

set_env() {
  MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  WORKSPACE_DIR="$( cd "${MY_DIR}/../.." && pwd )"
}

discover_pipeline_filenames() {
  PIPELINES_DIR="${MY_DIR}/pipelines"

  unset options
  i=0
  while IFS= read -r -d $'\0' f; do
    options[i++]="$f"
  done < <(find ${PIPELINES_DIR} -maxdepth 2 -type f -name "*.yml" -print0 )
}

prompt_user_for_pipeline() {
  echo "Please select a pipeline to 'fly set-pipeline':"
  echo

  select opt in "${options[@]}" "Exit"; do
    case $opt in
      *.yml)
  PIPELINE_PATH=$opt
  PIPELINE_FILENAME=$(basename ${PIPELINE_PATH})
  PIPELINE_NAME="${PIPELINE_FILENAME%.*}"
  echo
  echo "Configuring pipeline: ${PIPELINE_NAME} (${PIPELINE_PATH})"
  break
  ;;
      "Exit")
  echo
  echo "Exiting"
  exit
  ;;
      *)
  echo
  echo "Invalid choice. Exiting"
  exit
  ;;
    esac
  done
}

fly_pipeline() {
  FLY_TARGET="concourse"
  # if target is pws, don't use reconfigure-pipeline, since all credentials are in credhub
  if [[ ${PIPELINE_PATH} = *"/pws/"* ]]; then
    FLY_TARGET="pws"
  fi

  reconfigure-pipeline -t ${FLY_TARGET} set-pipeline \
    -p "${PIPELINE_NAME}" \
    -c "${PIPELINE_PATH}"

}

main() {
  set_env
  discover_pipeline_filenames
  prompt_user_for_pipeline
  fly_pipeline
}

main
