#!/bin/bash
set -eux

set_env(){
  MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  CI_DIR="$( cd "${MY_DIR}/../../" && pwd )"
  WORKSPACE_DIR="$( cd "${CI_DIR}/.." && pwd )"

  source "${CI_DIR}/scripts/utils.sh"

  : "${BOSH_LITE_SSH_KEY:?}"
  : "${ENV_TARGET_FILE:?}"
  : "${ENV_METADATA:?}"

  BOSH_TARGET=$(cat "${ENV_TARGET_FILE}")

  BOSH_CLIENT="$(jq_val "bosh_user" "${ENV_METADATA}")"
  BOSH_CLIENT_SECRET="$(jq_val "bosh_password" "${ENV_METADATA}")"
  GALERA_HEALTHCHECK_USERNAME="${GALERA_HEALTHCHECK_USERNAME:-galera-healthcheck}"

  bosh -n target "${BOSH_TARGET}"
  bosh -n login "${BOSH_CLIENT}" "${BOSH_CLIENT_SECRET}"
}

stop_all_nodes() {
  pushd "${WORKSPACE_DIR}"
    # assumes we are running against a remote bosh-lite
    BOSH_LITE_KEY_FILE="/tmp/id_rsa"
    echo "${BOSH_LITE_SSH_KEY}" > "${BOSH_LITE_KEY_FILE}"
    chmod 600 "${BOSH_LITE_KEY_FILE}"

    for nodeOctet in $(seq 7 9); do
      MYSQL_NODE=$"10.244.${nodeOctet}.2"
      if [[ $nodeOctet == 9 ]]; then
        MYSQL_NODE=$"10.244.${nodeOctet}.6"
      fi
      ssh \
          -t \
          -i "${BOSH_LITE_KEY_FILE}" \
          -o StrictHostKeyChecking=no \
          "ubuntu@${BOSH_TARGET}" \
          "curl -vkf -X POST ${GALERA_HEALTHCHECK_USERNAME}:password@${MYSQL_NODE}:9200/stop_mysql"
    done
  popd
}

main(){
    set_env
    stop_all_nodes
}

main
